Repository Sesostrismage/vc, pull requests merged in 2022-08, with the labels that each got.

#24 Updated requirements.txt
  requirements.txt
Labels: tech debt

#25 Changed month_dict into an Enum class.
  data_treat/maps.py
  scripts/09_histogram.py
  visuals/plotly_tools/figure.py
  visuals/plotly_tools/hovertext.py
  visuals/streamlit_tools.py
Labels: tech debt

#26 Now uses pathlib instead of os.
  data_io/files.py
  datasets/temp_brazil_cities/labeler.py
  definitions.py
  scripts/00_spyder_script.py
  scripts/01_streamlit_start.py
  scripts/03_file_automation.py
  scripts/04_consistent_colours.py
  scripts/05_reference_data_and_styling.py
  scripts/06_hovertext.py
  scripts/07_better_data_structure.py
  scripts/08_modular_code.py
  scripts/09_histogram.py
  scripts/10_heatmap.py
  scripts/11_correlation_plot.py
  scripts/12_phase_space_plot_outliers.py
  scripts/13_map_plot.py
  scripts/14_labeling.py
Labels: tech debt

#27 More realistic slider based on deviation from mean temperature.
  scripts/12_phase_space_plot_outliers.py
Labels: enhancement, tech debt

#28 Moved cdict inside the function so it can only be accessed that way.
  visuals/colors.py
Labels: tech debt

#29 Reorg
  data_treat/cities_data_treat.py
  scripts/03_file_automation.py
  scripts/04_consistent_colours.py
  scripts/05_reference_data_and_styling.py
  scripts/07_better_data_structure.py
  scripts/1_interactivity/i_01_spyder_script.py
  scripts/1_interactivity/i_02_streamlit_start.py
  scripts/1_interactivity/i_03_bokeh_labeling.py
  scripts/2_coding/c_01_f_string.py
  scripts/2_coding/c_02_file_automation.py
  scripts/2_coding/c_03_better_data_structure.py
  scripts/2_coding/c_04_modular_code.py
  scripts/2_coding/c_05_object_oriented_code.py
  scripts/3_visualization/v_01_consistent_colours_hovertext.py
  scripts/3_visualization/v_02_reference_data_and_styling.py
  scripts/3_visualization/v_03_fixed_axes.py
  scripts/3_visualization/v_04_table_styling.py
  scripts/3_visualization/v_05_histogram.py
  scripts/3_visualization/v_06_heatmap.py
  scripts/3_visualization/v_07_correlation_plot.py
  scripts/3_visualization/v_08_phase_space_plot_outliers.py
  scripts/3_visualization/v_09_map_plot.py
  visuals/colors.py
  visuals/plotly_tools/trace.py
  visuals/streamlit_tools.py
Labels: enhancement, tech debt

#31 Updated the readme for the scripts folder.
  scripts/readme.md
Labels: documentation
